# Generated by Django 4.2.2 on 2023-06-25 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("managment", "0002_extracapacitydetail_create_data_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="extracapacitydetail", name="residence",),
        migrations.RemoveField(model_name="standardcapacitydetail", name="residence",),
        migrations.AddField(
            model_name="residence",
            name="extra_capacity_detail",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="managment.extracapacitydetail",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="residence",
            name="standard_capacity_detail",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="managment.standardcapacitydetail",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="standardcapacitydetail",
            name="standard_capacity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="standardcapacitydetail",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
